# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/grafeas/grafeas
    environment:
            GOPATH: /go/:/go/src/github.com/grafeas/grafeas/samples/server/grafeas/go-server/api/server/storage:/usr/local/go/src/github.com/grafeas/grafeas/samples/server/grafeas/go-server/api/server/v1alpha1:/go/src/github.com/grafeas/grafeas/samples/server/grafeas/go-server/api/server/testing:/go/src/github.com/grafeas/grafeas/samples/server/grafeas/go-server/api/server/errors:/go/src/github.com/grafeas/grafeas/samples/server/grafeas/go-server/api/server/name
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
